openapi: 3.0.0
info:
  title: Compras Api
  description: Api para gerenciar compras, produtos e clientes.
  version: 1.0.0
paths:
  /clientes:
    get:
      summary: Retorna uma lista de clientes
      tags: [Clientes]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        cpf:
          type: string
      required:
        - nome
        - cpf
    Produto:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        descricao:
          type: string
        preco:
          type: number
      required:
        - nome
        - descricao
        - preco
    Pedido:
      type: object
      properties:
        id:
          type: integer
        dataPedido:
          type: string
          format: date
        total:
          type: number
        idCliente:
          type: integer
        itens:
          $ref: '#/components/schemas/ItemPedido'

      required:
        - dataPedido
        - idCliente
        - itens
    ItemPedido:
      type: object
      properties:
        id:
          type: integer
        idPedido:
          type: integer
        idProduto:
          type: number
        quantidade:
          type: number
        preco:
          type: number
        itemTotal:
          type: number
      required:
        - idPedido
        - idProduto
        - quantidade

